#!/usr/bin/env bash
# Script that makes loader inform about subdomains
#Usage: ./0-world_wide_web <domain> <subdomain>

if [ $# -eq 1 ]
then
    dom="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
    dom="$2.$1"
fi
dig $dom | awk '/ANSWER SECTION:/ { getline; split($1, a, "."); print "The subdomain", a[1], "is a", $4 " record and points to", $5}'
record=$(dig $domain  | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $4}')
        ip=$(dig $domain  | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $5}')
        echo "The subdomain $name is a $record record and points to $ip"
    else
        declare -a arr=("www" "lb-01" "web-01" "web-02")
        for i in "${arr[@]}"
        do
            domain=$i.$1
            name=$(dig $domain | grep -A1 'ANSWER SECTION:' | awk -F. 'NR==2 {print $1}')
            record=$(dig $domain  | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $4}')
            ip=$(dig $domain  | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $5}')
            echo "The subdomain $name is a $record record and points to $ip"
        done
    fi  
}

func $1 $2
