#!/usr/bin/env bash
# Script that makes loader inform about subdomains
Usage: ./0-world_wide_web <domain> <subdomain>
if [ $# -eq 1 ]
then
    dom="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
    dom="$2.$1"
fi
dig $dom | awk '/ANSWER SECTION:/ { getline; split($1, a, "."); print "The subdomain", a[1], "is a", $4 " record and points to", $5}'
