#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.7.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend nomoya.tech
        bind 0:80
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 50698-web-01 35.174.204.127:80
        server 50698-web-02 100.25.46.54:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
