#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.7
apt-get -y update
sudo apt-get install haproxy=2.7.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
listen load_balancer
bind *:80
mode http
balance roundrobin
option httpclose
option forwardfor
server 50698-web-01 35.174.204.127:80 check
server 50698-web-02 100.25.46.54:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
