#!/usr/bin/env bash
# back up and compress my datebases

mysqldump --all-databases -uroot -p"$1" > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
tar -czvf "$file_name" backup.sql
